include:
  - docker/libSQL/docker-compose.yml
services:
  pb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LIBSQL_URL=http://libsql-primary:8080
    ports:
      - "8090:8090"
    volumes:
      - pb-data:/app/db/pb_data
    depends_on:
      - libsql-primary

volumes:
  pb-data:
